bipedal_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60

  left_hip_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_hip_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_knee_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_knee_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_hip_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_hip_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_knee_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_knee_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}